emails:
  - days: 14
    hours: 10
    status: accepted
    subject: What dish would you like to bring to Potlucks for Change?
    body: >
    <p>Hi {{fname}},</p>
    <p>Thanks so much for signing up for the Potlucks for Change dinner happening on {{weekday}}, {{month_day}}.</p> 
    <p>When you get a chance, <a href="https://potlucks4change.web.app/?id={{reg_id}}" target="_blank">please let us know what dish you plan to bring here</a>. You can also list things like allergies to make sure that others attending are aware. </p>
    <p>Warm Regards,</p>
    <p>The Potlucks For Change Team</p>
  - days: 7
    hours: 10
    status: accepted
    subject: Upcoming Potlucks for Change Dinner – See you next week!
    body: > 
      <p>Hi {{fname}},</p>
        <p>I hope this email finds you well! I’m just reaching out to remind you of the Potlucks for Change dinner happening this {{weekday}}, {{month_day}}. We’re all set to welcome you at {{event_location}} at {{start_time}}.
        Here’s a quick recap of the evening:</p>
        <p>
        <p><b>Theme</b>: {{title}}</p>
        <p><b>Time</b>: {{start_time}}, {{weekday}} {{month_day}} (We’ll start with some appetizers and get to know each other!)</p>
        <p><b>Address</b>: {{event_location}}</p>
        <p><b>What to bring</b>: <a href="https://potlucks4change.web.app/?id={{reg_id}}" target="_blank">Sign up here</a> to share the dish or drinks you would like to contribute to the evening.</p>
        <p>We’re looking forward to an evening of warm conversation, delicious food, and actionable ideas on how we can collectively support reproductive freedom.
        A couple of quick reminders:</p>
        <ul>
        <li>If you have any dietary requirements or preferences, please let me know as soon as possible so we can accommodate everyone comfortably. You can do so using the dish signup link above.</li>
        {{parking_info}}
        {{transit_info}}
        </ul>
        <p>Feel free to reach out to {{host_name}} at {{host_phone}} if you have any questions.</p>
        See you soon at the dinner table for an evening of impactful dialogue and community building!</p>
        <p>Warm regards,</p>
        The Potlucks for Change Team</br>
  - days: 1
    hours: 10
    status: accepted
    subject: Upcoming Potlucks for Change Dinner – See you Tomorrow!
    body: >
      <p>Hi {{fname}},</p>
        <p>Super excited for the Potlucks for Change dinner happening tomorrow {{weekday}}, {{month_day}}. We’ll see you at {{event_location}} at {{start_time}}. 
        Here’s a quick recap of the evening:</p>
        <p><b>Theme</b>: {{title}}</br></p>
        <p><b>Time</b>: {{start_time}}, {{weekday}} {{month_day}} (We’ll start with some appetizers and get to know each other!)</br></p>
        <p><b>Address</b>: {{event_location}}</br></p>
        <p>We’re looking forward to an evening of warm conversation, delicious food, and actionable ideas on how we can collectively support reproductive freedom.
        We're excited to see you and want to double-check that you can still attend. If you cannot for any reason, please update the <a href="{{gcal_link}}" target="_blank">Google Calendar event</a> to let us know as soon as possible.</p>
              </div>
        <p>A couple of quick reminders:</p>
        <ul>
        <li>If you have any dietary restrictions or preferences, please let me know as soon as possible so we can accommodate everyone comfortably. You can do so using <a href="https://potlucks4change.web.app/?id={{reg_id}}" target="
        _blank">this link</a>.</li>
        {{parking_info}}
        {{transit_info}}
        <li>Feel free to reach out to {{host_name}} at {{host_phone}} if you have any questions.</li>
        </ul>
        <p>See you soon at the dinner table for an evening of impactful dialogue and community building!</p>
        <p>Warm regards,</p>
        The Postlucks for Change Team</br>
        
        <!-- HTML !-->
  - days: 0
    hours: 2
    status: accepted
    subject: Excited to see you at Potluck for Change! Here are directions.
    body: >
      <p>Hi {{fname}},</p>
        <p>We're very excited for the Potlucks for Change dinner happening at {{start_time}}! Here are <a href="https://www.google.com/maps/search/?api=1&query={{event_location}}" target="_blank">directions to {{event_location}}</a> in case they are helpful.</p>
        <ul>
        {{parking_info}}
        {{transit_info}}
        <li>Feel free to reach out to {{host_name}} at {{host_phone}} if you have any questions.</li>
        </ul>
        <p>See you soon for an evening of impactful dialogue and community building!</p>
        <p>Warm regards,</p>
        The Potlucks for Change Team</br>
