emails:
  - days: 7
    hours: 10
    status: "Accepted"
    subject: "Upcoming Potlucks for Change Dinner – See you next week!"
    body: > 
      "Hi {{fname}},
        I hope this email finds you well! I’m just reaching out to remind you of the Potlucks for Change dinner happening this {weekday}, {{month_day}}. We’re all set to welcome you at {{address}} at {{start_time}}.
        Here’s a quick recap of the evening:
        Theme: {{title}}
        Time: {{start_time}}, {{weekday}} {{month_day}} (We’ll start with some appetizers and get to know each other!)
        Address: {{address}}
        What to bring: Sign up here to share the dish or drinks you would like to contribute to the evening.
        We’re looking forward to an evening of warm conversation, delicious food, and actionable ideas on how we can collectively support reproductive freedom.
        A couple of quick reminders:
        If you have any dietary restrictions or preferences, please let me know as soon as possible so we can accommodate everyone comfortably. Using this link.
        Parking is available at {{parking_info}}, and the venue is {{transit_info}}.
        Feel free to reach out {{host_phone}}  if you have any questions or if there’s anything I can do to make your experience more enjoyable.
        See you soon at the dinner table for an evening of impactful dialogue and community building!
        Warm regards,
        {{host_name}}
        {{host_org}}
        {{host_phone}}"
  - days: 1
    hours: 10
    status: "Accepted"
    subject: "Can you make it to Potluck for Change tomorrow?"
    body: >
      "<p>Hi {{fname}},</p>
      <p>Just want confirm that you can make it to Potluck for Change tomorrow. We're excited to see you there!</p>
      <div style="display:flex"><button><a href='yes_link'>I can make it!</a></button><button><a href="no_link">Apologies, something's come up</a></div>
      <p>Thanks!</p>"
  - days: 0
    hours: 2
    status: "Accepted"
    subject: "Excited to see you at Potluck for Change! Here are directions."
    body: >
      "This is the body of the third email."